### ISSUE TITLE
Highlighting matching words

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_C#128]
### Scenario: 
  
  - User performs a text search and there are matching recipes
    
    ### Given: 
    
    - I am a user performing a text search for recipes in the app
    
    ### When: 
    
    - I enter my search text and perform the search
    
    ### Then: 
    
    - The matching words in the search results should be highlighted

**Comment by koketsobogopane** [comment]
I was able to set up what I think this feature should look like so even though the app is not working, when you add you query it will highlight the matching texts. Is this a solution?
